# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: WebApp Deploy to AzureStack using publish profile
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'testwebapp2'
          package: '.'
          publish-profile: ${{ secrets.AZURESTACK_WEBAPP_PUBLISHPROFILE }}